import React from 'react';
import MainLayout from '../components/layouts/MainLayout';
import StaticLayout from '../components/layouts/StaticLayout';
import { FileTextOutlined } from '@ant-design/icons';

const TermsAndConditions = () => {
  const sections = [
    {
      title: "Introduction",
      content: [
        "Welcome to JomVideo, a text-to-video AI generation platform.",
        "By accessing or using JomVideo, you agree to these Terms and Conditions. If you do not agree, you must stop using the Service.",
      ],
    },
    {
      title: "Definitions",
      content: [
        "“User”, “you”, or “your” refers to anyone accessing or using JomVideo.",
        "“Service” refers to the JomVideo website, platform, and related features.",
        "“Content” means text, prompts, images, videos, or other materials submitted by users or generated by the Service.",
      ],
    },
    {
      title: "Eligibility",
      content: [
        "You must be at least 18 years old (or the legal age in your jurisdiction) to use JomVideo.",
        "If using JomVideo on behalf of a business or organization, you confirm you have the authority to bind that entity to these Terms.",
      ],
    },
    {
      title: "User Accounts",
      content: [
        "You must provide accurate and complete information when creating an account.",
        "You are responsible for maintaining the confidentiality of your login credentials.",
        "You agree not to share your account or allow unauthorized access.",
      ],
    },
    {
      title: "Acceptable Use",
      content: [
        "You may not generate unlawful, defamatory, obscene, violent, hateful, discriminatory, or sexually explicit content.",
        "You may not create misleading or malicious deepfake content to impersonate others without consent.",
        "You may not upload content that infringes intellectual property rights.",
        "You may not reverse engineer, tamper with, or disrupt the Service.",
        "We may suspend or terminate your account if you violate these rules.",
      ],
    },
    {
      title: "Intellectual Property",
      content: [
        "You retain ownership of the prompts, inputs, and outputs you generate through JomVideo.",
        "By using the Service, you grant JomVideo a limited, worldwide, royalty-free license to process, store, and use your inputs and outputs for providing and improving the Service.",
        "JomVideo retains ownership of its platform, software, trademarks, designs, and all related intellectual property.",
      ],
    },
    {
      title: "Payments and Subscriptions",
      content: [
        "Some features may require payment or subscription.",
        "Fees are displayed at checkout and may change with prior notice.",
        "Payments are processed securely by third-party providers; JomVideo does not store your payment details.",
        "Except as required by law, all purchases are non-refundable.",
      ],
    },
    {
      title: "Disclaimers",
      content: [
        "The Service and all generated content are provided 'as is' and without warranties of any kind.",
        "JomVideo does not guarantee the accuracy, safety, or suitability of generated content.",
        "You acknowledge that AI-generated videos may contain errors, biases, or unintended results.",
      ],
    },
    {
      title: "Limitation of Liability",
      content: [
        "To the maximum extent permitted by law, JomVideo shall not be liable for indirect, incidental, special, or consequential damages.",
        "JomVideo’s total liability for any claim related to the Service shall not exceed the amount you paid for the Service in the past 12 months.",
      ],
    },
    {
      title: "Termination",
      content: [
        "We may suspend or terminate your account if you violate these Terms, misuse the Service, or for any reason at our discretion.",
        "You may close your account at any time through your account settings.",
      ],
    },
    {
      title: "Changes to Terms",
      content: [
        "We may update these Terms at any time.",
        "Changes will be posted with a new 'Last Updated' date.",
        "Continued use of the Service after changes constitutes acceptance of the new Terms.",
      ],
    }
  ];
  

  return (
    <StaticLayout
      title="Terms and Conditions"
      headerIcon={<FileTextOutlined />}
      lastUpdated="Last updated: August 2025"
      sections={sections}
    />
  );
};

export default TermsAndConditions;
